#
# Example using JSON format
#
trigger: none
pool:
  vmImage: "ubuntu-latest"

steps:

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.artifactstagingdirectory)'

  - task: Veracode@3
    inputs:
      ConnectionDetailsSelection: 'Service Connection'
      AnalysisService: 'Veracode'
      veracodeAppProfile: 'RobTest'
      version: '$(build.buildNumber)'
      filepath: '$(build.artifactstagingdirectory)'
      importResults: true
      failBuildOnPolicyFail: true
      maximumWaitTime: '360'

# container: checkmarx/kics:debian
# steps:
#   # running in CI mode, exporting results to a JSON file and printing the results in stdout
#   # KICS should fail the pipeline if results are found
#   - script: |
#       /app/bin/kics scan --ci -p ${PWD} -o ${PWD}
#       cat results.json
# #
# # Example using SARIF viewer:
# # https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab
# #

#   # run in CI mode, do not fail the pipeline on results found and export the report in both json and SARIF format.
#   - script: |
#       /app/bin/kics scan --ci -p ${PWD} -o ${PWD} --report-formats json,sarif --ignore-on-exit results
#       cat results.json
#   # scan results should be visible in the SARIF viewer tab of the build.
#   - task: PublishBuildArtifacts@1
#     inputs:
#       pathToPublish: $(System.DefaultWorkingDirectory)/results.sarif
#       artifactName: CodeAnalysisLogs

# #
# # Example using Checkmarx task
#   - task: Checkmarx AST@2
#     inputs:
#       CheckmarxService: 'Checkmarx One'
#       projectName: 'Artemystest/Checkmarx-POV/RobSauer-POV-Repo'
#       branchName: '$(Build.SourceBranchName)'
#       tenantName: 'symetra'
#       additionalParams: '--scan-types sast,iac-security'